version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html

hooks:
  ApplicationStop:
    - location: scripts/stop-nginx.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/setup-nginx-server.sh
      timeout: 300
      runas: root
  
  ApplicationStart:
    - location: scripts/start-nginx.sh
      timeout: 300
      runas: root

